### ISSUE TITLE
Adding Darkvision to Creature Doesn't Give Darkvision

### ISSUE THREAD

**Issue by Vaizt** [JDCalvert/FVTT-PF2e-Rules-Based-NPC-Vision#10]
Either I'm missing something or adding darkvision to a creature isn't working with vision enabled. The specific instance of this is on a guard dog as one summoned by the Wondrous Figurine(Onyx Dog) is meant to have darkvision.

**Comment by JDCalvert** [comment]
The token needs to have vision enabled for it to work, which is usually off by default. There is a core Foundry setting to set the Default Token Configuration, which allows you set vision to be enabled automatically.

Regarding the guard dog not having darkvision, there is no automation in place to add darkvision to the token if it is created from the item; you'll have to add darkvision to its senses manually.
