### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by AtreidesGhola** [JDCalvert/FVTT-PF2e-Rules-Based-NPC-Vision#9]
This module doesn't seem to work anymore.  With rules-based-vision and Perfect Vision installed and working otherwise, there's no NPC rbv available - it just keeps the general GM view.

**Comment by JDCalvert** [comment]
I've just had a try of this myself and everything seems to be working on my end.

Some things to check to help diagnose the problem:
- What version of Foundry are you using?
- What version of the Pathfinder 2e system are you using?
- Does the NPC's token have vision enabled (it's a checkbox in the token configuration)
- Does the NPC have any strangeness in its "senses" field?
